### ISSUE TITLE
dynamic Service / Action 

### ISSUE THREAD

**Issue by Splinter1984** [osrf/dynamic_message_introspection#21]
Hi.
Is there any way to support Services and Actions?

**Comment by christophebedard** [comment]
This should already work fine with services and actions if you use the actual underlying messages themselves, since the tools in this repo convert messages.

For example, [`example_interfaces::srv::AddTwoInts`](https://github.com/ros2/example_interfaces/blob/rolling/srv/AddTwoInts.srv) corresponds to two messages: the request and the response, respectively `example_interfaces::srv::AddTwoInts::Request` and `example_interfaces::srv::AddTwoInts::Response`. See the difference between normal pub/sub messages and service requests/response here: https://github.com/christophebedard/rmw_email/blob/c0110b6fc6a61f389ec58f54496c39f6026a4a13/rmw_email_cpp/src/conversion.cpp. [`yaml_to_msg_service()`](https://github.com/christophebedard/rmw_email/blob/c0110b6fc6a61f389ec58f54496c39f6026a4a13/rmw_email_cpp/src/conversion.cpp#L230) gets the right type support information (which is used to decode/encode the message into/from YAML) depending on whether the message is a request or a response, so from this point on, it's "just a normal message."

For actions, the messages are `::Goal`, `::Feedback`, and `::Result`.

**Comment by Splinter1984** [comment]
Hi, thank you for your response.
